apiVersion: v1
kind: Service
metadata:
  name: nginx-balancer
spec:
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
                                                            
