apiVersion: v1
kind: Service
metadata:
  name: kion-service-service
spec:
   type: LoadBalancer
   ports:
   - name: grpc
     port: 8082
     protocol: TCP
     targetPort: 8082
   - name: metrics
     port: 8888
     targetPort: 8888
   selector:
     app: kion-service
